name: Daily Investment Report

on:
  schedule:
    - cron: '30 22 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 버전 업그레이드

      - name: Set up Python
        uses: actions/setup-python@v5 # 버전 업그레이드
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install feedparser requests

      - name: Run script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        # 파일명이 news_bot.py가 맞는지 꼭 확인하세요!
        run: python newsnews_bot.py
